### ISSUE TITLE
Impossible to persist the removal of google auth

### ISSUE THREAD

**Issue by ryansanford** [flywheel-io/core#1361] opened 2018-08-15 18:56 UTC
Whenever uwsgi starts, even when google auth had been removed via the SCITRAN_AUTH_CONFIG_FILE file and the database, the default google auth entry sneaks into the database, and responses to /api/config

I suspect this is due to the default config containing a google entry because the `auth.google.client_id` value that sneaks in is the default in this repo, and not the site-specific one that had been removed.. https://github.com/flywheel-io/core/blob/master/api/config.py#L56

This is a customer facing issue reproducible with core version 3.0.0. A different site running core 2.5.3 doesn't seem to be impacted, so this may be a recent regression.

**Comment by ryansanford** [comment] 2018-08-27 14:20
@nagem How soon can this get addressed given current priorities?

**Comment by hkethi002** [comment] 2018-08-27 19:58
@ryansanford I was able to reproduce this on master but not on #1353, the entries were sneaking in because we were updating the current auth from the config so it wouldn't unset any entries, the PR makes it a replace so that any entries not in the SCITRAN_AUTH_CONFIG_FILE are removed

**Comment by nagem** [comment] 2019-01-14 23:49
Resolved by #1353

**Closed by nagem** 2019-01-14 23:49 UTC
Labels: Bug, High Priority
